"""Emit outputs: cartograph.json, draft Source Card, replay snippets."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from argus.cartographer.capture import CapturedRequest, CapturedWebSocket, EmbeddedState
from argus.core.source_card import (
    Defenses,
    DiscoveredEndpoint,
    SourceCard,
    WebSocketConfig,
)
from argus.core.source_card import (
    save as save_card,
)

SOURCES_ROOT = Path("sources")


@dataclass
class CartographResult:
    source_id: str
    pillar: str
    url: str
    recommended_tier: int
    top_endpoints: list[CapturedRequest]
    websockets: list[CapturedWebSocket]
    embedded_states: list[EmbeddedState]
    all_requests: list[CapturedRequest]
    har_path: str = ""
    trace_path: str = ""


def emit_json(result: CartographResult) -> Path:
    """Write the full classified inventory to sources/<pillar>/<id>.cartograph.json."""
    out_dir = SOURCES_ROOT / result.pillar
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{result.source_id}.cartograph.json"

    def _req_dict(r: CapturedRequest) -> dict:
        return {
            "url": r.url,
            "method": r.method,
            "status": r.status,
            "content_type": r.content_type,
            "resource_type": r.resource_type,
            "body_bytes": r.body_bytes,
            "data_likelihood": round(r.data_likelihood, 3),
            "is_noise": r.is_noise,
            "request_headers": r.request_headers,
            "body_snippet": r.body_text[:500] if r.body_text else "",
        }

    payload: dict[str, Any] = {
        "source_id": result.source_id,
        "pillar": result.pillar,
        "url": result.url,
        "recommended_tier": result.recommended_tier,
        "top_data_endpoints": [_req_dict(r) for r in result.top_endpoints],
        "websockets": [
            {
                "url": ws.url,
                "subscribe_frames": [
                    {"payload": f.payload, "decoded": f.decoded} for f in ws.subscribe_frames
                ],
                "sample_received": [
                    {"payload": f.payload, "decoded": f.decoded} for f in ws.sample_received
                ],
            }
            for ws in result.websockets
        ],
        "embedded_states": [
            {"global_var": s.global_var, "path": s.path, "sample": s.sample}
            for s in result.embedded_states
        ],
        "all_requests_count": len(result.all_requests),
        "har_path": result.har_path,
        "trace_path": result.trace_path,
    }
    out_path.write_text(json.dumps(payload, indent=2, default=str))
    return out_path


def emit_source_card(result: CartographResult) -> Path:
    """Write a draft Source Card YAML populated with discovered endpoints."""
    discovered: list[DiscoveredEndpoint] = []
    for req in result.top_endpoints[:5]:
        # Exclude cookies from the headers (rotated per session; not replay-safe)
        safe_headers = {
            k: v
            for k, v in req.request_headers.items()
            if k.lower() not in ("cookie", "authorization", "set-cookie")
        }
        discovered.append(
            DiscoveredEndpoint(
                method=req.method,
                url_template=req.url,
                headers_required=safe_headers,
                auth="cookie" if "cookie" in req.request_headers else "none",
                response_path="",
                data_likelihood=round(req.data_likelihood, 3),
            )
        )

    ws_config: WebSocketConfig | None = None
    if result.websockets:
        ws = result.websockets[0]
        subscribe_msg = ""
        if ws.subscribe_frames:
            subscribe_msg = ws.subscribe_frames[0].payload
        ws_config = WebSocketConfig(url=ws.url, subscribe_msg=subscribe_msg)

    card = SourceCard(
        id=result.source_id,
        name=result.source_id.replace("_", " ").title(),
        url=result.url,
        pillar=result.pillar,  # type: ignore[arg-type]
        tier=result.recommended_tier,
        status="LIVE",
        discovered_endpoints=discovered,
        websocket=ws_config,
        defenses=Defenses(),
        har_path=result.har_path,
        trace_path=result.trace_path,
        notes="Draft — generated by Cartographer. Review and fill response_path, cadence, robots_ok.",
    )
    return save_card(card)


def emit_snippets(result: CartographResult) -> Path:
    """Write httpx + curl_cffi replay snippets for the top endpoints."""
    out_dir = SOURCES_ROOT / result.pillar
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{result.source_id}.snippets.py"

    lines: list[str] = [
        '"""Auto-generated replay snippets from Cartographer. Review before use."""',
        "",
        "import asyncio",
        "import httpx",
        "from curl_cffi.requests import AsyncSession",
        "",
    ]

    for i, req in enumerate(result.top_endpoints[:3], 1):
        safe_headers = {
            k: v
            for k, v in req.request_headers.items()
            if k.lower() not in ("cookie", "set-cookie")
        }
        header_repr = repr(safe_headers)

        lines += [
            f"# ── Endpoint {i}: {req.url[:80]} ──",
            f"# data_likelihood={req.data_likelihood:.2f}  method={req.method}",
            "",
            f"async def replay_{i}_httpx():",
            "    async with httpx.AsyncClient() as client:",
            f"        resp = await client.{req.method.lower()}(",
            f"            {req.url!r},",
            f"            headers={header_repr},",
            "        )",
            "        return resp.json()",
            "",
            f"async def replay_{i}_curl_cffi():",
            '    async with AsyncSession(impersonate="chrome124") as session:',
            f"        resp = await session.{req.method.lower()}(",
            f"            {req.url!r},",
            f"            headers={header_repr},",
            "        )",
            "        return resp.json()",
            "",
        ]

    if result.websockets:
        ws = result.websockets[0]
        sub = ws.subscribe_frames[0].payload if ws.subscribe_frames else ""
        lines += [
            f"# ── WebSocket: {ws.url[:80]} ──",
            "import websockets",
            "",
            "async def tap_websocket():",
            f"    async with websockets.connect({ws.url!r}) as wss:",
            f"        await wss.send({sub!r})",
            "        async for msg in wss:",
            "            print(msg)",
            "",
        ]

    lines += [
        'if __name__ == "__main__":',
        "    asyncio.run(replay_1_curl_cffi())",
    ]

    out_path.write_text("\n".join(lines))
    return out_path
